//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EATApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Core.Metadata.Edm;

    public partial class session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public session()
        {
            this.studentsessions = new HashSet<studentsession>();
        }
    
        public int sessionID { get; set; }
        public string Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public string LecturerID { get; set; }
        public string Code { get; set; }
    
        public virtual lecturer lecturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentsession> studentsessions { get; set; }

    }
}
