//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EATApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class studentsession
    {
        private string studentID;
        private int sessionID;
        private System.TimeSpan signIn;

        public studentsession()
        {
            this.studentID = "DEFAULT";
            this.sessionID = -1;
            this.signIn = DateTime.Now.TimeOfDay;
        }

        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public System.TimeSpan SignIn { get; set; }

        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.TimeSpan> SignOut { get; set; }
        public int session_sessionID { get; set; }
        public string student_StudentID { get; set; }
    
        public virtual session session { get; set; }
        public virtual student student { get; set; }

        public studentsession(string studentID, int sessionID, System.TimeSpan signIn)
        {
            this.student_StudentID = studentID;
            this.session_sessionID = sessionID;
            this.SignIn = signIn;
        }

    }
}
