//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EATApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSession
    {
        public string SessionID { get; set; }
        public int StudentID { get; set; }
        public string SignIn { get; set; }
        public string SignOut { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual Student Student { get; set; }
    }
}
